version: '3'
services:
  webkubectl:
    image: ghcr.io/mentoredtestbed/webkubectl:latest
    environment:
      - GOTTY_OPTIONS=--permit-arguments --port 8080 --permit-write
    privileged: true
    ports:
      - "8081:8080"

  frontend-build:
    build:
      context: .
      dockerfile: Dockerfile.frontend-build
    network_mode: "host"
    command: /app/frontend-build-entrypoint.sh
    volumes:
      - ./build-prod:/build
      - .env:/app/.env.production

  tutorial-build:
    build:
      context: .
      dockerfile: Dockerfile.tutorial-build
    network_mode: "host"
    command: /app/tutorial-build-entrypoint.sh
    volumes:
      - ./build-tutorial-prod:/build-tutorial

  mentored-backend:
    build:
      context: .
      dockerfile: mentored-backend/Dockerfile
    restart: always
    command: uwsgi --socket 0.0.0.0:3031 --master --buffer-size=65535 --wsgi-file sp_django/wsgi.py --chmod-socket=666 --enable-threads --processes 2 --lazy-apps -t 600 --post-buffering 2097152 --post-buffering-bufsize 2097152 --ini uwsgi_config.ini

    ports:
      - "3031:3031"
    volumes:
      - ./experiment-data-path:/experiment-data-path/
      - ./certificates:/app/certificates/
      - ./mentored-backend:/app/
      - ./kubeconfig:/root/.kube/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile.nginx-server-prod
    network_mode: "host"
    volumes:
      - ./build-prod/dist:/usr/share/nginx/html
      - ./build-tutorial-prod/site:/mkdocs_tutorial/
      - ./cert.cer:/etc/ssl/certs/mentored-cert.cer
      - ./cert.key:/etc/ssl/private/mentored-cert.key
    depends_on:
      - mentored-backend

