apiVersion: v1
kind: Pod
metadata:
  namespace: mentored
  name: server
  annotations:
    # kubernetes.io/ingress-bandwidth: 1M
    # kubernetes.io/egress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/ingress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/egress-bandwidth: 1M
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-whx-sc
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-whx-df
    # k8s.v1.cni.cncf.io/networks: macvlan-dhcp-ids-pe
    # k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-ids-df
    k8s.v1.cni.cncf.io/networks: macvlan-3169-mentored-whx-es
    # k8s.v1.cni.cncf.io/networks: '[
    #         { "name": "macvlan-static-whx-sc",
    #           "ips": [ "10.1.1.3/24" ],
    #           "gateway": [ "10.1.1.7" ]
    #         }]'
    # k8s.v1.cni.cncf.io/networks: '[
    #         { "name": "macvlan-whx-pe",
    #           "ips": [ "10.1.1.3/24" ],
    #           "gateway": [ "10.1.1.7" ]
    #         }]'
  labels:
    actor: server
spec:
  # nodeName: whx-sc
  # nodeName: whx-df
  # nodeName: ids-pe
  # nodeName: ids-df
  nodeName: whx-es
  volumes:
    - name: nginx-pv-storage
      persistentVolumeClaim:
        claimName: meuapp-pvc2
  containers:
  - name: tcpdump
    image: allexmagno/tcpdump
    imagePullPolicy: "IfNotPresent"
    #command: ["/bin/sh"]
    #args: ["-c", "while true; do echo hello; sleep 10;done"]
    command: ["tcpdump"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
    args: ["-i", "net1", "-w","pcaps/server.pcap"]
    volumeMounts:
      - mountPath: "/app/pcaps/"
        name: nginx-pv-storage
  - name: nginx
    image: nginx
    imagePullPolicy: "IfNotPresent"
    ports:
      - containerPort: 80
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
    # resources:
    #   requests:
    #     memory: "1G"
    #     cpu: "1"
    #   limits:
    #     memory: "2G"
    #     cpu: "2"
  nodeSelector:
#    kubernetes.io/hostname: whx-sc
    # kubernetes.io/hostname: whx-df
    # kubernetes.io/hostname: ids-pe
    # kubernetes.io/hostname: ids-df
    kubernetes.io/hostname: whx-es
